### ISSUE TITLE
Ajustar combo y datos a imagen

### ISSUE THREAD

**Issue by EdgarGra** [pixelead0/odd_mty#1]
Hola, favor de ajustar los elementos a la nueva imagen y ver la posibilidad de que quede centrado a la pantalla.
![perfil_html_seguros_monterrey_final copy](https://cloud.githubusercontent.com/assets/22689325/19204740/2f412452-8ca4-11e6-8432-466170e1ead6.png)

Muchas gracias,
Edgar

**Comment by pixelead0** [comment]
Se han aplicado los cambios solicitados.


*--*

*AdanGQ <http://about.me/adangq>*tw: @pixelead0
<http://www.twitter.com/pixelead0>


2016-10-07 15:39 GMT-05:00 EdgarGra <notifications@github.com>:
